
#Server configuration
server:
    port: 8080

#Database configuration
db:
    #Types
    # -postgresql
    # -sqlite
    type: sqlite

#SQLite configuration
sqlite:
    pathdir: db/data
    filename: db.db

#Postgres configuration
#postgresql:
#
